name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up C++ build environment
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake qtbase5-dev qt5-qmake qml-module-qtquick-controls2 qtdeclarative5-dev git

    - name: Install microcdr
      run: |
        git clone https://github.com/eProsima/Micro-CDR
        cd Micro-CDR
        mkdir build && cd build
        cmake ..
        make
        sudo make install
        # cd ../..

    - name: Install microxrcedds_client
      run: |
        git clone https://github.com/eProsima/Micro-XRCE-DDS-Client.git
        cd Micro-XRCE-DDS-Client
        mkdir build && cd build
        cmake ..
        make
        sudo make install
        # cd ../..

    - name: Configure the project
      run: cmake -S . -B build

    - name: Build the project
      run: cmake --build build --config Release

    - name: Run tests
      run: ./build/CombatDisplay

  analyze:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: CodeQL Analysis
      uses: github/codeql-action/init@v2
      with:
        languages: cpp

    - name: Perform CodeQL Analysis
      run: |
        codeql database create --language=cpp --output=codeql-db
        codeql database analyze codeql-db --format=sarif-latest --output=codeql-analysis.sarif

  format:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Clang-Format
      run: sudo apt-get install -y clang-format

    - name: Format code
      run: clang-format -i **/*.cpp **/*.h

    - name: Check for formatting issues
      run: git diff --exit-code
