name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: cmake/setup-cmake@v3
        with:
          cmake-version: '3.24' # Adjust to your required version

      - name: Install dependencies
        run: sudo apt-get install -y build-essential libqt5widgets5 qt5-qmake

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: List build directory contents
        run: ls -la build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build

  analyze:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Print working directory
        run: pwd

      - name: List root directory contents
        run: ls -la

      - name: List downloaded artifact directory contents
        run: ls -la Combat-Display-System

      - name: List build directory contents
        run: ls -la Combat-Display-System/build

      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Run cppcheck
        run: cppcheck --enable=all --std=c++11 --force src include

      - name: Install clang-tidy
        run: sudo apt-get install -y clang-tidy

      - name: Run clang-tidy
        run: clang-tidy -p=Combat-Display-System/build src/*.cpp include/*.h