name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up C++ build environment
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake git

    - name: Install Qt5
      run: |
        sudo apt-get install -y qtbase5-dev qt5-qmake qml-module-qtquick-controls2 qtdeclarative5-dev

    - name: Install microcdr
      run: |
        git clone https://github.com/eProsima/Micro-CDR
        cd Micro-CDR
        mkdir build && cd build
        cmake ..
        make
        sudo make install

    - name: Install microxrcedds_client
      run: |
        git clone https://github.com/eProsima/Micro-XRCE-DDS-Client.git
        cd Micro-XRCE-DDS-Client
        mkdir build && cd build
        cmake ..
        make
        sudo make install

    - name: Configure the project
      run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: List build directory
      run: ls -l build

    - name: Build the project
      run: cmake --build build --config Release

    - name: Run tests
      run: ./build/CombatDisplay

  analyze:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck

    - name: Run cppcheck
      run: cppcheck --enable=all --std=c++11 --force src include

    - name: Install clang-tidy
      run: sudo apt-get install -y clang-tidy

    - name: List build directory
      run: ls -l build

    - name: Run clang-tidy
      run: clang-tidy -p=build src/*.cpp include/*.h

  format:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Clang-Format
      run: sudo apt-get install -y clang-format

    - name: Format code
      run: clang-format -i **/*.cpp **/*.h

    - name: Check for formatting issues
      run: git diff --exit-code