name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up C++ build environment
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake qtbase5-dev qt5-qmake qml-module-qtquick-controls2 qtdeclarative5-dev git

    - name: Install microcdr and microxrcedds_client from source
      run: |
        # Install microcdr
        git clone https://github.com/eProsima/microcdr.git
        cd microcdr
        mkdir build && cd build
        cmake ..
        sudo make install
        cd ../..

        # Install microxrcedds_client
        git clone https://github.com/eProsima/Micro-XRCE-DDS-Client.git
        cd Micro-XRCE-DDS-Client
        mkdir build && cd build
        cmake ..
        sudo make install
        cd ../..

    - name: Configure the project
      run: cmake -S . -B build

    - name: Build the project
      run: cmake --build build --config Release

    - name: Run tests
      run: ./build/CombatDisplay
